name: Playwright Tests
on:
  push:
    branches: [ main, apitests ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      env:
        TRELLO_KEY: ${{ secrets.KEY }}
        TRELLO_TOKEN: ${{ secrets.TOKEN }}
        TRELLO_LOGIN: ${{ secrets.LOGIN }}
        TRELLO_PASSWORD: ${{ secrets.PASSWORD }}
      run: KEY=$TRELLO_KEY TOKEN=$TRELLO_TOKEN LOGIN=$TRELLO_LOGIN PASSWORD=$TRELLO_PASSWORD npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
